name: CI-CD-Pipeline-2-AWS-Beanstalk

env:
  EB_PACKAGE_S3_BUCKET_NAME: "github-beanstalk-bucket"
  EB_APP_NAME: "MyFlaskApp"
  EB_ENV_NAME: "Myflaskapp-env"
  DEPLOY_PKG_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "us-west-2"

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repository
        uses: actions/checkout@v1

      - name: Create zip deployment pkg
        run: zip -r ${{ env.DEPLOY_PKG_NAME }} ./ -x *.git*

      - name: Show files
        run: ls -lah
