name: CI-CD-Pipeline-2-AWS-Beanstalk

env:
  EB_PACKAGE_S3_BUCKET_NAME: "github-beanstalk-bucket"
  EB_APP_NAME: "MyFlaskApp"
  EB_ENV_NAME: "Myflaskapp-env"
  DEPLOY_PKG_NAME: "flask_app_${{ github.sha }}.zip"
  AWS_REGION_NAME: "us-west-2"

on:
  push:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Git clone repository
        uses: actions/checkout@v1

      - name: Create zip deployment pkg
        run: zip -r ${{ env.DEPLOY_PKG_NAME }} ./ -x *.git*

      - name: Show files
        run: ls -lah

      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}

      - name: Copy Deployment pkg to S3 bucket
        run: aws s3 cp ${{ env.DEPLOY_PKG_NAME }} s3://${{ env.EB_PACKAGE_S3_BUCKET_NAME }}

      - name: Deployment complete
        run: echo "deployment complete!"

  CD:
    runs-on: ubuntu-latest
    needs: [CI]

    steps:
      - name: Configure AWS creds
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_SECRET_KEY}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION_NAME }}
      - name: Create new ElasticBeanstalk Application
        run: |
          aws elasticbeanstalk create-application-version \
          --aplication-name ${{ env.EB_APP_NAME }}
          --source-bundle S3Bucket="${{ env.EB_PACKAGE_S3_BUCKET_NAME }}",S3Key="${{env.DEPLOY_PKG_NAME}}" \
          --version-label "Ver-${{ github.sha }}
          --description "CommitSHA-${{ github.sha }}"

      - name: Deploy new ElasticBeanstalk Application
        run: aws elasticbeanstalk update-environment --environment-name ${{ env.EB_ENV_NAME }} \
        --version-label "Ver-${{ github.sha }}"

      - name: CD Pipeline Finish
        run: echo "deply is complete"